version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: game_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - game_network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: game_php
    volumes:
      - ./:/var/www/html
    networks:
      - game_network

  mysql:
    image: mysql:8.0
    container_name: game_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: game_db
      MYSQL_USER: gameuser
      MYSQL_PASSWORD: gamepass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - game_network

networks:
  game_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local