version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game_php
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/be-game-bahasaku
    networks:
      - game_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: game_mysql
    restart: unless-stopped
    ports:
      - "3307:3307"  # Changed to 3307 to avoid conflict
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game_db
      MYSQL_USER: gameuser
      MYSQL_PASSWORD: gamepass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - game_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  game_network:
    driver: bridge

volumes:
  mysql_data: